Add server extension status
kiteco/jupyterlab-kite pull request #64
Opened 2020-10-06 21:27 UTC by ryantberg

Fixes kiteco/kiteco#11866

2020-10-06 22:03 UTC, tonycheang approved these changes

2020-10-06 22:07 UTC, edzkite commented on packages/jupyterlab-kite/src/adapters/jupyterlab/components/status_model.ts
> +    if (response.status === 404) {
Would it work if we did `!response.ok || response.status !==200`?

2020-10-07 20:02 UTC, ryantberg commented on packages/jupyterlab-kite/src/adapters/jupyterlab/components/status_model.ts
> +    if (response.status === 404) {
I'm not sure under what circumstances a non-{200,404} code would be returned, but if that happens we probably don't want to direct users towards checking that `jupyter-kite` is installed. Not sure what messaging would be most appropriate, but we do have the console warning on 49.

2020-10-08 21:24 UTC, edzkite requested changes

2020-10-08 21:24 UTC, edzkite commented on packages/jupyterlab-kite/src/adapters/jupyterlab/components/status_model.ts
> +        this._onChange();
This would cause an infinite loop. `_onChange` will re-render the status bar item, which calls `fetchKiteInstalled` again.

2020-10-08 21:24 UTC, edzkite commented on packages/jupyterlab-kite/src/adapters/jupyterlab/components/status_model.ts
> +      this._onChange();
See above comment on `_onChange`

2020-10-08 21:24 UTC, edzkite commented on packages/jupyterlab-kite/src/adapters/jupyterlab/components/status_model.ts
> +    if (response.status === 404) {
We should consider augmenting the messaging to something like "check jupyter-kite is installed or see [kite help link] for more information". 

From user feedback, many of them do have `jupyter-kite` installed, but are still experiencing 404s.

In any case, I think it should be okay just check for `!response.ok` which covers anything outside of a 2xx.

2020-10-08 21:25 UTC, edzkite commented
@ryantberg I'm considering streamlining the status/installed checks a little bit. Feel free to close the PR or hand it off to me.

2020-10-08 22:09 UTC, ryantberg commented
@edzkite that sounds fine to me. I'll close this one.

2020-10-08 22:09 UTC, closed without merging